// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Interface$ReactTemplate = require("./Interface.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Interface$ReactTemplate.make(/* array */[])), "main");

/*  Not a pure module */
