// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Main$ReactTemplate = require("./Main.bs.js");

var component = ReasonReact.reducerComponent("Example");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", undefined, React.createElement("textarea", {
                              onChange: (function (_event) {
                                  return Curry._1(self[/* send */3], /* Update */[_event.target.value]);
                                })
                            }), React.createElement("br", undefined), React.createElement("button", {
                              onClick: (function () {
                                  return Curry._1(self[/* send */3], /* Click */0);
                                })
                            }, "Interpret"), React.createElement("button", {
                              onClick: (function () {
                                  return Curry._1(self[/* send */3], /* Clear */1);
                                })
                            }, "Clear"), React.createElement("br", undefined), React.createElement("p", undefined, self[/* state */1][/* text */1]));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* code */"",
                      /* text */""
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                if (action !== 0) {
                  return /* Update */Block.__(0, [/* record */[
                              /* code */state[/* code */0],
                              /* text */""
                            ]]);
                } else {
                  return /* Update */Block.__(0, [/* record */[
                              /* code */state[/* code */0],
                              /* text */state[/* text */1] + Main$ReactTemplate.interpete(state[/* code */0])
                            ]]);
                }
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* code */action[0],
                            /* text */state[/* text */1]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
