// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var $$String = require("bs-platform/lib/js/string.js");
var StdDef$ReactTemplate = require("./StdDef.bs.js");
var ImutHash$ReactTemplate = require("./ImutHash.bs.js");

var string_mod = ImutHash$ReactTemplate.add("concat", /* Fonction */Block.__(12, [/* NativeF */Block.__(0, [(function (tokens) {
                var chaines = List.map(StdDef$ReactTemplate.to_string, tokens);
                var chaine = $$String.concat(" ", chaines);
                return /* Chaine */Block.__(3, [chaine]);
              })])]), ImutHash$ReactTemplate.empty);

StdDef$ReactTemplate.set_value("String", /* Struct */Block.__(13, [string_mod]));

var vars = StdDef$ReactTemplate.vars;

var get_value = StdDef$ReactTemplate.get_value;

var set_value = StdDef$ReactTemplate.set_value;

var add_stack = StdDef$ReactTemplate.add_stack;

var remove_stack = StdDef$ReactTemplate.remove_stack;

var get_stack = StdDef$ReactTemplate.get_stack;

var get_var = StdDef$ReactTemplate.get_var;

var sortie = StdDef$ReactTemplate.sortie;

var to_int = StdDef$ReactTemplate.to_int;

var to_float = StdDef$ReactTemplate.to_float;

var to_char = StdDef$ReactTemplate.to_char;

var to_string = StdDef$ReactTemplate.to_string;

var to_sym = StdDef$ReactTemplate.to_sym;

var to_bool = StdDef$ReactTemplate.to_bool;

var to_array = StdDef$ReactTemplate.to_array;

var to_block = StdDef$ReactTemplate.to_block;

var to_function = StdDef$ReactTemplate.to_function;

var run = StdDef$ReactTemplate.run;

var tok_get = StdDef$ReactTemplate.tok_get;

var tok_calc = StdDef$ReactTemplate.tok_calc;

var run_fun = StdDef$ReactTemplate.run_fun;

var look_at = StdDef$ReactTemplate.look_at;

exports.vars = vars;
exports.get_value = get_value;
exports.set_value = set_value;
exports.add_stack = add_stack;
exports.remove_stack = remove_stack;
exports.get_stack = get_stack;
exports.get_var = get_var;
exports.sortie = sortie;
exports.to_int = to_int;
exports.to_float = to_float;
exports.to_char = to_char;
exports.to_string = to_string;
exports.to_sym = to_sym;
exports.to_bool = to_bool;
exports.to_array = to_array;
exports.to_block = to_block;
exports.to_function = to_function;
exports.run = run;
exports.tok_get = tok_get;
exports.tok_calc = tok_calc;
exports.run_fun = run_fun;
exports.look_at = look_at;
exports.string_mod = string_mod;
/* string_mod Not a pure module */
